var inputstream = [{
  "washrooms": [{
    "PRIMARYIND": 1,
    "PLACE": "Adanac Park",
    "ADDRESS": "1025 Boundary Road",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "East side, fieldhouse",
    "SUMMER_HOURS": "Dawn to Dusk",
    "WINTER_HOURS": "Dawn to Dusk",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "",
    "LATITUDE": 49.2758809678,
    "LONGITUDE": -123.0240719603,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 2,
    "PLACE": "Andy Livingstone Park",
    "ADDRESS": "89 Expo Boulevard",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "South side, fieldhouse",
    "SUMMER_HOURS": "12:00 pm - 4:00 pm",
    "WINTER_HOURS": "12:00 pm - 4:00 pm",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "",
    "LATITUDE": 49.2778209665,
    "LONGITUDE": -123.1035990223,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 3,
    "PLACE": "Balaclava Park",
    "ADDRESS": "4594 Balaclava Street",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "Central, field house",
    "SUMMER_HOURS": "Dawn to Dusk",
    "WINTER_HOURS": "Dawn to Dusk",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "Caretaker on site",
    "LATITUDE": 49.2452339944,
    "LONGITUDE": -123.1754609494,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 4,
    "PLACE": "Barclay Heritage Square",
    "ADDRESS": "1433 Barclay Street",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "Barclay Manor (WECC)",
    "SUMMER_HOURS": "Hours of the centre",
    "WINTER_HOURS": "Hours of the centre",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "",
    "LATITUDE": 49.2872148698,
    "LONGITUDE": -123.1325605109,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 5,
    "PLACE": "Beaconsfield Park",
    "ADDRESS": "3215 Slocan Street",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "East side, fieldhouse",
    "SUMMER_HOURS": "Dawn to Dusk",
    "WINTER_HOURS": "Dawn to Dusk",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "Caretaker on site",
    "LATITUDE": 49.2552329902,
    "LONGITUDE": -123.0499339593,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 6,
    "PLACE": "Bobolink Park",
    "ADDRESS": "2510 Hoylake Avenue",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "North side, fieldhouse",
    "SUMMER_HOURS": "Dawn to Dusk",
    "WINTER_HOURS": "Dawn to Dusk",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "Caretaker on site",
    "LATITUDE": 49.2156069867,
    "LONGITUDE": -123.056414955,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 7,
    "PLACE": "Braemar Park",
    "ADDRESS": "895 W 27th Avenue",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "East edge, fieldhouse",
    "SUMMER_HOURS": "Dawn to Dusk",
    "WINTER_HOURS": "Dawn to Dusk",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "Caretaker on site",
    "LATITUDE": 49.2474209947,
    "LONGITUDE": -123.1244830217,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 8,
    "PLACE": "Brewers Park",
    "ADDRESS": "4175 Victoria Drive",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "North east corner fieldhouse",
    "SUMMER_HOURS": "Dawn to Dusk",
    "WINTER_HOURS": "Closed",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "Caretaker on site",
    "LATITUDE": 49.2478549907,
    "LONGITUDE": -123.0654259491,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 9,
    "PLACE": "Burrard View Park",
    "ADDRESS": "650 North Penticton Street",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "Fieldhouse",
    "SUMMER_HOURS": "Dawn to Dusk",
    "WINTER_HOURS": "Dawn to Dusk",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "",
    "LATITUDE": 49.2903639622,
    "LONGITUDE": -123.0496489708,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 10,
    "PLACE": "CRAB Park at Portside",
    "ADDRESS": "101 E Waterfront Road",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "South side at fieldhouse",
    "SUMMER_HOURS": "7:00 am - Dusk",
    "WINTER_HOURS": "7:00 am - Dusk",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "Caretaker on site",
    "LATITUDE": 49.2845920073,
    "LONGITUDE": -123.1018350041,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 11,
    "PLACE": "Carnarvon Park",
    "ADDRESS": "2995 W 19th Avenue",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "West side, field house",
    "SUMMER_HOURS": "Dawn to Dusk",
    "WINTER_HOURS": "Dawn to Dusk",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "",
    "LATITUDE": 49.2567420169,
    "LONGITUDE": -123.1726090104,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 12,
    "PLACE": "Chaldecott Park",
    "ADDRESS": "4175 Wallace Street",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "East side fieldhouse",
    "SUMMER_HOURS": "Dawn to Dusk",
    "WINTER_HOURS": "Dawn to Dusk",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "Caretaker on site",
    "LATITUDE": 49.2494269601,
    "LONGITUDE": -123.1911249621,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 13,
    "PLACE": "Clinton Park",
    "ADDRESS": "2690 Grant Street",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "North east corner, fieldhouse",
    "SUMMER_HOURS": "Dawn to Dusk",
    "WINTER_HOURS": "Dawn to Dusk",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "",
    "LATITUDE": 49.2711450329,
    "LONGITUDE": -123.0497820279,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 14,
    "PLACE": "Collingwood Park",
    "ADDRESS": "5275 McKinnon Street",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "South corner, fieldhouse",
    "SUMMER_HOURS": "Dawn to Dusk",
    "WINTER_HOURS": "Dawn to Dusk",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "",
    "LATITUDE": 49.2365299637,
    "LONGITUDE": -123.0367159607,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 15,
    "PLACE": "Columbia Park",
    "ADDRESS": "5908 Alberta Street",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "",
    "SUMMER_HOURS": "Dawn to Dusk Weekends only",
    "WINTER_HOURS": "Dawn to Dusk Weekends only",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "",
    "LATITUDE": 49.2315229979,
    "LONGITUDE": -123.112908974,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 16,
    "PLACE": "David Lam Park",
    "ADDRESS": "1300 Pacific Boulevard",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "West side",
    "SUMMER_HOURS": "10:00 am - Dusk",
    "WINTER_HOURS": "10:00 am - Dusk",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "",
    "LATITUDE": 49.2723830073,
    "LONGITUDE": -123.1254150352,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 17,
    "PLACE": "Elm Park",
    "ADDRESS": "5800 Elm Street",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "Central, field house",
    "SUMMER_HOURS": "Dawn to Dusk",
    "WINTER_HOURS": "Dawn to Dusk",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "",
    "LATITUDE": 49.2334319792,
    "LONGITUDE": -123.1632839446,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 18,
    "PLACE": "English Bay Beach Park",
    "ADDRESS": "1700 Beach Avenue",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "Bathhouse",
    "SUMMER_HOURS": "7:00 am - Dusk",
    "WINTER_HOURS": "10:00 am - Dusk",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "",
    "LATITUDE": 49.28615404,
    "LONGITUDE": -123.1428049671,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 19,
    "PLACE": "Falaise Park",
    "ADDRESS": "3434 Falaise Avenue",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "Community Hall",
    "SUMMER_HOURS": "Dawn to Dusk",
    "WINTER_HOURS": "Dawn to Dusk",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "Womens is closed Mon - Fri during school days",
    "LATITUDE": 49.2551230347,
    "LONGITUDE": -123.0294059867,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 20,
    "PLACE": "Fraser River Park",
    "ADDRESS": "8705 Angus Drive",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "West corner",
    "SUMMER_HOURS": "Dawn to Dusk",
    "WINTER_HOURS": "Closed",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "Open April 1 to October 31",
    "LATITUDE": 49.2073949986,
    "LONGITUDE": -123.1498560045,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 21,
    "PLACE": "Fraserview Golf Course",
    "ADDRESS": "7800 Vivian Drive",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "Kerr Road @13th hole",
    "SUMMER_HOURS": "Dawn to Dusk",
    "WINTER_HOURS": "Dawn to Dusk",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "",
    "LATITUDE": 49.2112953518,
    "LONGITUDE": -123.0422996676,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 22,
    "PLACE": "Garden Park",
    "ADDRESS": "1851 Garden Drive",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "North east corner, fieldhouse",
    "SUMMER_HOURS": "Dawn to Dusk",
    "WINTER_HOURS": "Dawn to Dusk",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "Caretaker on site",
    "LATITUDE": 49.2682859984,
    "LONGITUDE": -123.058333994,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 23,
    "PLACE": "Gordon Park",
    "ADDRESS": "6675 Commercial Street",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "East side",
    "SUMMER_HOURS": "Dawn to Dusk",
    "WINTER_HOURS": "Dawn to Dusk",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "",
    "LATITUDE": 49.2238700451,
    "LONGITUDE": -123.0694999785,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 24,
    "PLACE": "Grandview Park",
    "ADDRESS": "1657 Charles Street",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "South side",
    "SUMMER_HOURS": "Dawn to Dusk",
    "WINTER_HOURS": "Dawn to Dusk",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "",
    "LATITUDE": 49.2737616313,
    "LONGITUDE": -123.0699544464,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 25,
    "PLACE": "Granville Park",
    "ADDRESS": "3001 Fir Street",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "Central, field house",
    "SUMMER_HOURS": "Dawn to Dusk",
    "WINTER_HOURS": "Dawn to Dusk",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "",
    "LATITUDE": 49.2584930115,
    "LONGITUDE": -123.1419699499,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 26,
    "PLACE": "Grays Park",
    "ADDRESS": "4850 St. Catherines Street",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "Centre west by parking lot",
    "SUMMER_HOURS": "During playground program hours",
    "WINTER_HOURS": "Closed",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "Open April 1 to October 31",
    "LATITUDE": 49.2407870046,
    "LONGITUDE": -123.0848870327,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 27,
    "PLACE": "Hadden Park",
    "ADDRESS": "1905 Ogden Avenue",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "West, caretaker house (actually in Kits)",
    "SUMMER_HOURS": "Dawn to Dusk",
    "WINTER_HOURS": "Dawn to Dusk",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "",
    "LATITUDE": 49.2774609931,
    "LONGITUDE": -123.1503099821,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 28,
    "PLACE": "Harbour Green Park",
    "ADDRESS": "1199 W Cordova Street",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "Central",
    "SUMMER_HOURS": "8:00 am - Dusk",
    "WINTER_HOURS": "10:00 am - Dusk",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "",
    "LATITUDE": 49.2898040141,
    "LONGITUDE": -123.1214669986,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 29,
    "PLACE": "Hastings Community Park",
    "ADDRESS": "3000 E Pender Street",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "Central, field house",
    "SUMMER_HOURS": "Dawn to Dusk",
    "WINTER_HOURS": "Closed",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "",
    "LATITUDE": 49.2806479708,
    "LONGITUDE": -123.0378739491,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 30,
    "PLACE": "Jericho Beach Park",
    "ADDRESS": "3941 Point Grey Road",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "Service Yard - public exterior attached to service building",
    "SUMMER_HOURS": "Dawn to Dusk",
    "WINTER_HOURS": "Dawn - 11:00 pm",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "",
    "LATITUDE": 49.274427989,
    "LONGITUDE": -123.2028059987,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 31,
    "PLACE": "Jericho Beach Park",
    "ADDRESS": "3941 Point Grey Road",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "Concession/fieldhouse",
    "SUMMER_HOURS": "Dawn to Dusk",
    "WINTER_HOURS": "Dawn to Dusk",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "Caretaker on site",
    "LATITUDE": 49.2715800213,
    "LONGITUDE": -123.1916589596,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 32,
    "PLACE": "John Hendry (Trout Lake) Park",
    "ADDRESS": "3300 Victoria Drive",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "At Trout Lake",
    "SUMMER_HOURS": "6:00 am - 8:30 pm",
    "WINTER_HOURS": "6:00 am - 8:30 pm",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "Caretaker on site",
    "LATITUDE": 49.2539260389,
    "LONGITUDE": -123.0613879889,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 33,
    "PLACE": "Jonathan Rogers Park",
    "ADDRESS": "110 W 7th Avenue",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "North side, fieldhouse",
    "SUMMER_HOURS": "Dawn to Dusk",
    "WINTER_HOURS": "Dawn to Dusk",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "Caretaker on site",
    "LATITUDE": 49.2644980299,
    "LONGITUDE": -123.1076200161,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 34,
    "PLACE": "Jones Park",
    "ADDRESS": "5350 Commercial Street",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "North west corner, fieldhouse",
    "SUMMER_HOURS": "Dawn to Dusk",
    "WINTER_HOURS": "Dawn to Dusk",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "Caretaker on site",
    "LATITUDE": 49.236204959,
    "LONGITUDE": -123.0683280271,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 35,
    "PLACE": "Kitsilano Beach Park",
    "ADDRESS": "1499 Arbutus Street",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "Kitsilano Showboat concession",
    "SUMMER_HOURS": "Dawn to Dusk",
    "WINTER_HOURS": "Closed",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "Caretaker on site",
    "LATITUDE": 49.273014034,
    "LONGITUDE": -123.1575429676,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 36,
    "PLACE": "Kitsilano Beach Park",
    "ADDRESS": "1499 Arbutus Street",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "Lifeguard station",
    "SUMMER_HOURS": "Dawn to Dusk",
    "WINTER_HOURS": "Dawn to Dusk",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "",
    "LATITUDE": 49.2744719936,
    "LONGITUDE": -123.1537029747,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 37,
    "PLACE": "Locarno Park",
    "ADDRESS": "4445 NW Marine Drive",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "Concession at fieldhouse",
    "SUMMER_HOURS": "Dawn to Dusk",
    "WINTER_HOURS": "Dawn to Dusk",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "Caretaker on site",
    "LATITUDE": 49.2750659923,
    "LONGITUDE": -123.2065550131,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 38,
    "PLACE": "MacLean Park",
    "ADDRESS": "710 Keefer Street",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "North west corner, fieldhouse",
    "SUMMER_HOURS": "Dawn to Dusk",
    "WINTER_HOURS": "Dawn to Dusk",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "",
    "LATITUDE": 49.2790070229,
    "LONGITUDE": -123.0893660404,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 39,
    "PLACE": "Maple Grove Park",
    "ADDRESS": "6875 Yew Street",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "Central, field house",
    "SUMMER_HOURS": "Dawn to Dusk",
    "WINTER_HOURS": "Dawn to Dusk",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "Caretaker on site",
    "LATITUDE": 49.2233840215,
    "LONGITUDE": -123.1595829747,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 40,
    "PLACE": "McBride Park",
    "ADDRESS": "3350 W 4th Avenue",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "Central, field house",
    "SUMMER_HOURS": "Dawn to Dusk",
    "WINTER_HOURS": "Dawn to Dusk",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "",
    "LATITUDE": 49.2681069665,
    "LONGITUDE": -123.1801409622,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 41,
    "PLACE": "Memorial South Park",
    "ADDRESS": "5955 Ross Street",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "Oval",
    "SUMMER_HOURS": "Dawn to 11:15 pm",
    "WINTER_HOURS": "Dawn to 11:15 pm",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "",
    "LATITUDE": 49.2307380348,
    "LONGITUDE": -123.0843880026,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 42,
    "PLACE": "Memorial West Park",
    "ADDRESS": "4701 Dunbar Street",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "Central, field house",
    "SUMMER_HOURS": "Dawn to Dusk",
    "WINTER_HOURS": "Dawn to Dusk",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "Caretaker on site",
    "LATITUDE": 49.2433349852,
    "LONGITUDE": -123.1884550031,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 43,
    "PLACE": "Moberly Park",
    "ADDRESS": "7646 Prince Albert Street",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "South west corner at Community Hall",
    "SUMMER_HOURS": "Dawn to Dusk",
    "WINTER_HOURS": "Dawn to Dusk",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "",
    "LATITUDE": 49.2152529959,
    "LONGITUDE": -123.0873549789,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 44,
    "PLACE": "Montgomery Park",
    "ADDRESS": "1040 W 43rd Avenue",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "North east corner",
    "SUMMER_HOURS": "Dawn to Dusk",
    "WINTER_HOURS": "Dawn to Dusk",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "Caretaker on site",
    "LATITUDE": 49.2318260466,
    "LONGITUDE": -123.1292409865,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 45,
    "PLACE": "Nanaimo Park",
    "ADDRESS": "2390 E 46th Avenue",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "North side, fieldhouse",
    "SUMMER_HOURS": "Dawn to Dusk",
    "WINTER_HOURS": "Dawn to Dusk",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "Caretaker on site",
    "LATITUDE": 49.228241999,
    "LONGITUDE": -123.057429042,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 46,
    "PLACE": "New Brighton Park",
    "ADDRESS": "3201 New Brighton Road",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "South side of pool building",
    "SUMMER_HOURS": "Dawn to Dusk",
    "WINTER_HOURS": "Dawn to Dusk",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "Caretaker on site",
    "LATITUDE": 49.28933397,
    "LONGITUDE": -123.0360250074,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 47,
    "PLACE": "New Brighton Park",
    "ADDRESS": "3201 New Brighton Road",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "North east corner, fieldhouse",
    "SUMMER_HOURS": "Dawn to Dusk",
    "WINTER_HOURS": "Dawn to Dusk",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "Caretaker on site",
    "LATITUDE": 49.289293,
    "LONGITUDE": -123.036308,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 48,
    "PLACE": "Norquay Park",
    "ADDRESS": "5050 Wales Street",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "West side, field house",
    "SUMMER_HOURS": "Dawn to Dusk",
    "WINTER_HOURS": "Dawn to Dusk",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "",
    "LATITUDE": 49.2379749903,
    "LONGITUDE": -123.0514249599,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 49,
    "PLACE": "Oak Park",
    "ADDRESS": "900 W 59th Avenue",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "East side field house",
    "SUMMER_HOURS": "Dawn to Dusk",
    "WINTER_HOURS": "Dawn to Dusk",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "",
    "LATITUDE": 49.2162859951,
    "LONGITUDE": -123.1276409787,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 50,
    "PLACE": "Oppenheimer Park",
    "ADDRESS": "400 Powell Street",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "North east corner",
    "SUMMER_HOURS": "Tue - Sat 9:00 am - 8:00 pm",
    "WINTER_HOURS": "Tue - Sat 9:00 am - 5:00 pm",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "Family washroom available",
    "LATITUDE": 49.2829379682,
    "LONGITUDE": -123.0941810354,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 51,
    "PLACE": "Pandora Park",
    "ADDRESS": "2325 Franklin Street",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "South side, fieldhouse",
    "SUMMER_HOURS": "9:00 am - 7:00 pm",
    "WINTER_HOURS": "Closed",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "",
    "LATITUDE": 49.2822799987,
    "LONGITUDE": -123.0574780492,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 52,
    "PLACE": "Prince Edward Park",
    "ADDRESS": "3773 Prince Edward Street",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "South east corner, fieldhouse",
    "SUMMER_HOURS": "Dawn to Dusk",
    "WINTER_HOURS": "Dawn to Dusk",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "Caretaker on site",
    "LATITUDE": 49.2511909721,
    "LONGITUDE": -123.0970569942,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 53,
    "PLACE": "Queen Elizabeth Park",
    "ADDRESS": "4600 Cambie Street",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "Lookout",
    "SUMMER_HOURS": "7:30 am - 9:00 pm",
    "WINTER_HOURS": "7:30 am - 9:00 pm",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "",
    "LATITUDE": 49.2421839651,
    "LONGITUDE": -123.1129190034,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 54,
    "PLACE": "Queen Elizabeth Park",
    "ADDRESS": "4600 Cambie Street",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "Fieldhouse",
    "SUMMER_HOURS": "Dawn to Dusk",
    "WINTER_HOURS": "Dawn to Dusk",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "",
    "LATITUDE": 49.2389380178,
    "LONGITUDE": -123.1115770566,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 55,
    "PLACE": "Queen Elizabeth Park",
    "ADDRESS": "4600 Cambie Street",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "Under \"Seasons",
    "SUMMER_HOURS": "7:30 am - 9:00 pm",
    "WINTER_HOURS": "7:30 am - 9:00 pm",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "",
    "LATITUDE": 49.2422110177,
    "LONGITUDE": -123.1128449753,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 56,
    "PLACE": "Quilchena Park",
    "ADDRESS": "4590 Magnolia Street",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "North east corner, fieldhouse",
    "SUMMER_HOURS": "Dawn to Dusk",
    "WINTER_HOURS": "Dawn to Dusk",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "Caretaker on site",
    "LATITUDE": 49.2446430483,
    "LONGITUDE": -123.1487239449,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 57,
    "PLACE": "Riverfront Park",
    "ADDRESS": "2750 E Kent Street S",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "North side",
    "SUMMER_HOURS": "Dawn to Dusk",
    "WINTER_HOURS": "Dawn to Dusk",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "",
    "LATITUDE": 49.2057680376,
    "LONGITUDE": -123.0518469707,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 58,
    "PLACE": "Robson Park",
    "ADDRESS": "599 Kingsway",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "",
    "SUMMER_HOURS": "Dawn to Dusk",
    "WINTER_HOURS": "Dawn to Dusk",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "Caretaker on site",
    "LATITUDE": 49.2586270164,
    "LONGITUDE": -123.0928489868,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 59,
    "PLACE": "Ross Park",
    "ADDRESS": "7402 Ross Street",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "South west corner, fieldhouse",
    "SUMMER_HOURS": "Dawn to Dusk",
    "WINTER_HOURS": "Dawn to Dusk",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "",
    "LATITUDE": 49.2166999807,
    "LONGITUDE": -123.082798035,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 60,
    "PLACE": "Rupert Park",
    "ADDRESS": "1600 Rupert Street",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "South side, fieldhouse",
    "SUMMER_HOURS": "Dawn to Dusk",
    "WINTER_HOURS": "Dawn to Dusk",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "Caretaker on site",
    "LATITUDE": 49.2701350042,
    "LONGITUDE": -123.0306049796,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 61,
    "PLACE": "Rupert Park",
    "ADDRESS": "1600 Rupert Street",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "Pitch & Putt (north side)",
    "SUMMER_HOURS": "Dawn to Dusk",
    "WINTER_HOURS": "Dawn to Dusk",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "",
    "LATITUDE": 49.2730500016,
    "LONGITUDE": -123.0306829593,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 62,
    "PLACE": "Slocan Park",
    "ADDRESS": "2750 E 29th Avenue",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "North side",
    "SUMMER_HOURS": "Dawn to Dusk",
    "WINTER_HOURS": "Dawn to Dusk",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "",
    "LATITUDE": 49.2444379784,
    "LONGITUDE": -123.0479520172,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 63,
    "PLACE": "Spanish Banks Beach Park",
    "ADDRESS": "4801 NW Marine Drive",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "West, fieldhouse",
    "SUMMER_HOURS": "Dawn to Dusk",
    "WINTER_HOURS": "Dawn to Dusk",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "",
    "LATITUDE": 49.277471986,
    "LONGITUDE": -123.2226790554,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 64,
    "PLACE": "Spanish Banks Beach Park",
    "ADDRESS": "4801 NW Marine Drive",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "East, fieldhouse",
    "SUMMER_HOURS": "Dawn to Dusk",
    "WINTER_HOURS": "Dawn to Dusk",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "Caretaker on site",
    "LATITUDE": 49.2762439755,
    "LONGITUDE": -123.2149200375,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 65,
    "PLACE": "Stanley Park",
    "ADDRESS": "2000 W Georgia Street",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "Service yard",
    "SUMMER_HOURS": "Mon - Fri 7:00 am - 3:30 pm",
    "WINTER_HOURS": "Mon - Fri 7:00 am - 3:30 pm",
    "WHEELCHAIR_ACCESS": "Accessible",
    "NOTE": "Wheelchair accessible",
    "LATITUDE": 49.2999400358,
    "LONGITUDE": -123.1366829512,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 66,
    "PLACE": "Stanley Park",
    "ADDRESS": "2000 W Georgia Street",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "Totems",
    "SUMMER_HOURS": "5:30 am - Dusk",
    "WINTER_HOURS": "7:30 am - Dusk",
    "WHEELCHAIR_ACCESS": "Accessible",
    "NOTE": "Wheelchair accessible",
    "LATITUDE": 49.2994400235,
    "LONGITUDE": -123.1212780196,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 67,
    "PLACE": "Stanley Park",
    "ADDRESS": "2000 W Georgia Street",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "Train, Picnic Shelter",
    "SUMMER_HOURS": "5:30 am - Dusk",
    "WINTER_HOURS": "9:00 am - Dusk",
    "WHEELCHAIR_ACCESS": "Accessible",
    "NOTE": "Wheelchair accessible",
    "LATITUDE": 49.3020690032,
    "LONGITUDE": -123.1329230422,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 68,
    "PLACE": "Stanley Park",
    "ADDRESS": "2000 W Georgia Street",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "Brockton Oval",
    "SUMMER_HOURS": "5:30 am - Dusk",
    "WINTER_HOURS": "5:30 am - Dusk",
    "WHEELCHAIR_ACCESS": "Accessible",
    "NOTE": "Wheelchair accessible",
    "LATITUDE": 49.2996259646,
    "LONGITUDE": -123.1260230026,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 69,
    "PLACE": "Stanley Park",
    "ADDRESS": "2000 W Georgia Street",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "Park Board Main office",
    "SUMMER_HOURS": "Weekdays only 8:30 am - 5:00 pm",
    "WINTER_HOURS": "Weekdays only 8:30 am - 5:00 pm",
    "WHEELCHAIR_ACCESS": "Accessible",
    "NOTE": "Wheelchair accessible",
    "LATITUDE": 49.2908669672,
    "LONGITUDE": -123.1453549644,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 70,
    "PLACE": "Stanley Park",
    "ADDRESS": "2000 W Georgia Street",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "2nd Beach, fieldhouse",
    "SUMMER_HOURS": "7:00 am - Dusk",
    "WINTER_HOURS": "7:00 am - Dusk",
    "WHEELCHAIR_ACCESS": "Accessible",
    "NOTE": "Wheelchair accessible",
    "LATITUDE": 49.2956269926,
    "LONGITUDE": -123.1507330006,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 71,
    "PLACE": "Stanley Park",
    "ADDRESS": "2000 W Georgia Street",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "3rd Beach, fieldhouse",
    "SUMMER_HOURS": "7:00 am - Dusk",
    "WINTER_HOURS": "7:00 am - Dusk",
    "WHEELCHAIR_ACCESS": "Yes, at parking lot level",
    "NOTE": "Wheelchair accessible at parking lot level",
    "LATITUDE": 49.303152992,
    "LONGITUDE": -123.1559310487,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 72,
    "PLACE": "Stanley Park",
    "ADDRESS": "2000 W Georgia Street",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "Aquarium plaza",
    "SUMMER_HOURS": "7:00 am - Dusk",
    "WINTER_HOURS": "7:00 am - Dusk",
    "WHEELCHAIR_ACCESS": "Accessible",
    "NOTE": "Wheelchair accessible",
    "LATITUDE": 49.299867996,
    "LONGITUDE": -123.1307000049,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 73,
    "PLACE": "Stanley Park",
    "ADDRESS": "2000 W Georgia Street",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "Ceperley Picnic Shelter",
    "SUMMER_HOURS": "May 1- Sept 30  7:00 am - Dusk",
    "WINTER_HOURS": "Closed",
    "WHEELCHAIR_ACCESS": "Accessible",
    "NOTE": "Wheelchair accessible",
    "LATITUDE": 49.2936169901,
    "LONGITUDE": -123.1487149567,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 74,
    "PLACE": "Stanley Park",
    "ADDRESS": "2000 W Georgia Street",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "Chilco",
    "SUMMER_HOURS": "8:00 am - Dusk",
    "WINTER_HOURS": "10:00 am - Dusk",
    "WHEELCHAIR_ACCESS": "Accessible",
    "NOTE": "Wheelchair accessible",
    "LATITUDE": 49.2939220383,
    "LONGITUDE": -123.1385910294,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 75,
    "PLACE": "Stanley Park",
    "ADDRESS": "2000 W Georgia Street",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "Fish House",
    "SUMMER_HOURS": "7:00 am - Dusk",
    "WINTER_HOURS": "10:00 am - Dusk",
    "WHEELCHAIR_ACCESS": "Yes, key available at Pitch and Putt ticket booth",
    "NOTE": "Key to accessible washroom on west side of Fish House available at Pitch and Putt Golf Course ticket booth",
    "LATITUDE": 49.2922930216,
    "LONGITUDE": -123.1465800409,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 76,
    "PLACE": "Stanley Park",
    "ADDRESS": "2000 W Georgia Street",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "Info Booth",
    "SUMMER_HOURS": "7:00 am - Dusk",
    "WINTER_HOURS": "10:00 am - Dusk",
    "WHEELCHAIR_ACCESS": "Accessible",
    "NOTE": "Wheelchair accessible",
    "LATITUDE": 49.2977530147,
    "LONGITUDE": -123.1314329661,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 77,
    "PLACE": "Stanley Park",
    "ADDRESS": "2000 W Georgia Street",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "Lumbermans Arch",
    "SUMMER_HOURS": "5:30 am - Dusk",
    "WINTER_HOURS": "5:30 am - Dusk",
    "WHEELCHAIR_ACCESS": "Accessible",
    "NOTE": "Wheelchair accessible",
    "LATITUDE": 49.3029259847,
    "LONGITUDE": -123.130707979,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 78,
    "PLACE": "Stanley Park",
    "ADDRESS": "2000 W Georgia Street",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "Pavilion",
    "SUMMER_HOURS": "5:30 am - Dusk",
    "WINTER_HOURS": "7:00 am - Dusk",
    "WHEELCHAIR_ACCESS": "Yes, entered from parking lot level",
    "NOTE": "Accessible washroom entered from parking lot level, to the left side of the building.",
    "LATITUDE": 49.2995490315,
    "LONGITUDE": -123.1340510161,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 79,
    "PLACE": "Stanley Park",
    "ADDRESS": "2000 W Georgia Street",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "Pitch & Putt Golf Course",
    "SUMMER_HOURS": "9:00 am - Dusk",
    "WINTER_HOURS": "9:00 am - Dusk",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "Not accessible, key to accessible washroom on west side of Fish House available at ticket booth",
    "LATITUDE": 49.2930350373,
    "LONGITUDE": -123.1465990248,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 80,
    "PLACE": "Stanley Park",
    "ADDRESS": "2000 W Georgia Street",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "Prospect Point",
    "SUMMER_HOURS": "7:00 am - Dusk",
    "WINTER_HOURS": "7:00 am - Dusk",
    "WHEELCHAIR_ACCESS": "Accessible",
    "NOTE": "Wheelchair accessible",
    "LATITUDE": 49.3124120321,
    "LONGITUDE": -123.1426499893,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 81,
    "PLACE": "Stanley Park",
    "ADDRESS": "2000 W Georgia Street",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "Prospect Point Picnic, fieldhouse",
    "SUMMER_HOURS": "Dawn to Dusk",
    "WINTER_HOURS": "Dawn to Dusk",
    "WHEELCHAIR_ACCESS": "Accessible",
    "NOTE": "Wheelchair accessible",
    "LATITUDE": 49.3105500284,
    "LONGITUDE": -123.1483880399,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 82,
    "PLACE": "Strathcona Park",
    "ADDRESS": "857 Malkin Avenue",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "South side, fieldhouse",
    "SUMMER_HOURS": "Dawn to Dusk",
    "WINTER_HOURS": "Dawn to Dusk",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "",
    "LATITUDE": 49.2745570066,
    "LONGITUDE": -123.0861889918,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 83,
    "PLACE": "Sunrise Park",
    "ADDRESS": "1950 Windermere Street",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "North west corner, fieldhouse",
    "SUMMER_HOURS": "Dawn to Dusk",
    "WINTER_HOURS": "Dawn to Dusk",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "",
    "LATITUDE": 49.2669229919,
    "LONGITUDE": -123.0360179825,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 84,
    "PLACE": "Sunset Beach Park",
    "ADDRESS": "1204 Beach Avenue",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "Concession",
    "SUMMER_HOURS": "Dawn to Dusk",
    "WINTER_HOURS": "7:00 am - Dusk",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "Caretaker on site",
    "LATITUDE": 49.2788370148,
    "LONGITUDE": -123.1379500435,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 85,
    "PLACE": "Tatlow Park",
    "ADDRESS": "2845 W 3rd Avenue",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "South, field house",
    "SUMMER_HOURS": "Dawn to Dusk",
    "WINTER_HOURS": "Dawn to Dusk",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "Caretaker on site",
    "LATITUDE": 49.2694760118,
    "LONGITUDE": -123.1695119497,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 86,
    "PLACE": "Trafalgar Park",
    "ADDRESS": "2610 W 23rd Avenue",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "North side, fieldhouse",
    "SUMMER_HOURS": "Dawn to Dusk",
    "WINTER_HOURS": "Dawn to Dusk",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "Caretaker on site",
    "LATITUDE": 49.2515549664,
    "LONGITUDE": -123.1634719734,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 87,
    "PLACE": "Trillium Park",
    "ADDRESS": "600 National Avenue",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "",
    "SUMMER_HOURS": "Dawn to 10:15 pm",
    "WINTER_HOURS": "Dawn to 10:15 pm",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "",
    "LATITUDE": 49.2748,
    "LONGITUDE": -123.0929110423,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 88,
    "PLACE": "VanDusen Botanical Garden",
    "ADDRESS": "5251 Oak Street",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "Floral hall",
    "SUMMER_HOURS": "Hours of operation only",
    "WINTER_HOURS": "Hours of operation only",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "",
    "LATITUDE": 49.2385104499,
    "LONGITUDE": -123.1286383402,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 89,
    "PLACE": "VanDusen Botanical Garden",
    "ADDRESS": "5251 Oak Street",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "At front entrance",
    "SUMMER_HOURS": "Hours of operation only",
    "WINTER_HOURS": "Hours of operation only",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "",
    "LATITUDE": 49.2386594327,
    "LONGITUDE": -123.1295576458,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 90,
    "PLACE": "Vanier Park",
    "ADDRESS": "1000 Chestnut Street",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "Burrard Civic Marina",
    "SUMMER_HOURS": "Dawn to Dusk",
    "WINTER_HOURS": "Dawn to Dusk",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "Sometimes later in summer",
    "LATITUDE": 49.2751960118,
    "LONGITUDE": -123.1398559437,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 91,
    "PLACE": "Victoria Park",
    "ADDRESS": "1425 Victoria Drive",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "West side",
    "SUMMER_HOURS": "Dawn to Dusk",
    "WINTER_HOURS": "Dawn to Dusk",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "",
    "LATITUDE": 49.2717440428,
    "LONGITUDE": -123.0674130165,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 92,
    "PLACE": "West Point Grey Park",
    "ADDRESS": "2250 Trimble Street",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "Centre",
    "SUMMER_HOURS": "Dawn to Dusk",
    "WINTER_HOURS": "Dawn to Dusk",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "",
    "LATITUDE": 49.2665415434,
    "LONGITUDE": -123.2045795644,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 93,
    "PLACE": "Winona Park",
    "ADDRESS": "7575 Columbia Street",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "Fieldhouse",
    "SUMMER_HOURS": "Dawn to Dusk",
    "WINTER_HOURS": "Dawn to Dusk",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "Caretaker on site",
    "LATITUDE": 49.2157179804,
    "LONGITUDE": -123.1129489453,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 94,
    "PLACE": "Woodland Park",
    "ADDRESS": "705 Woodland Drive",
    "TYPE": "Washroom in Park",
    "PHYSICAL_LOCATION": "Central, field house",
    "SUMMER_HOURS": "Dawn to Dusk",
    "WINTER_HOURS": "Dawn to Dusk",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "Caretaker on site",
    "LATITUDE": 49.2783689722,
    "LONGITUDE": -123.0732200047,
    "MAINTAINER": "Parks"
  },
  {
    "PRIMARYIND": 95,
    "PLACE": "Main at Hastings",
    "ADDRESS": "",
    "TYPE": "Comfort Station",
    "PHYSICAL_LOCATION": "SW corner of intersection",
    "SUMMER_HOURS": "Men: 6am, Women: 8am to Midnight",
    "WINTER_HOURS": "Men: 6am, Women: 8am to Midnight",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "N/A",
    "LATITUDE": 49.281107,
    "LONGITUDE": -123.09985,
    "MAINTAINER": "City"
  },
  {
    "PRIMARYIND": 96,
    "PLACE": "Victory Square",
    "ADDRESS": "",
    "TYPE": "Comfort Station",
    "PHYSICAL_LOCATION": "N/A",
    "SUMMER_HOURS": "Men: 6am, Women: 8am to Midnight",
    "WINTER_HOURS": "Men: 6am, Women: 8am to Midnight",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "N/A",
    "LATITUDE": 49.2825906,
    "LONGITUDE": -123.110132,
    "MAINTAINER": "City"
  },
  {
    "PRIMARYIND": 97,
    "PLACE": "Main at Terminal",
    "ADDRESS": "",
    "TYPE": "Automated Public Toilet",
    "PHYSICAL_LOCATION": "NE corner of intersection",
    "SUMMER_HOURS": "24 hrs",
    "WINTER_HOURS": "24 hrs",
    "WHEELCHAIR_ACCESS": "Accessible",
    "NOTE": "Please call 311 for maintenance requests",
    "LATITUDE": 49.2731387,
    "LONGITUDE": -123.099778,
    "MAINTAINER": "City"
  },
  {
    "PRIMARYIND": 98,
    "PLACE": "Richards at Davie - Emery Barnes Park",
    "ADDRESS": "",
    "TYPE": "Automated Public Toilet",
    "PHYSICAL_LOCATION": "NW corner of intersection",
    "SUMMER_HOURS": "24 hrs",
    "WINTER_HOURS": "24 hrs",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "Please call 311 for maintenance requests",
    "LATITUDE": 49.2760544,
    "LONGITUDE": -123.124114,
    "MAINTAINER": "City"
  },
  {
    "PRIMARYIND": 99,
    "PLACE": "Nelson at Howe",
    "ADDRESS": "",
    "TYPE": "Automated Public Toilet",
    "PHYSICAL_LOCATION": "NE corner of intersection",
    "SUMMER_HOURS": "24 hrs",
    "WINTER_HOURS": "24 hrs",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "Please call 311 for maintenance requests",
    "LATITUDE": 49.2796964,
    "LONGITUDE": -123.123516,
    "MAINTAINER": "City"
  },
  {
    "PRIMARYIND": 100,
    "PLACE": "Powell at Main",
    "ADDRESS": "",
    "TYPE": "Automated Public Toilet",
    "PHYSICAL_LOCATION": "NW corner of intersection",
    "SUMMER_HOURS": "24 hrs",
    "WINTER_HOURS": "24 hrs",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "Please call 311 for maintenance requests",
    "LATITUDE": 49.2832763,
    "LONGITUDE": -123.099849,
    "MAINTAINER": "City"
  },
  {
    "PRIMARYIND": 101,
    "PLACE": "Robson at Richards",
    "ADDRESS": "",
    "TYPE": "Automated Public Toilet",
    "PHYSICAL_LOCATION": "NW corner of intersection",
    "SUMMER_HOURS": "24 hrs",
    "WINTER_HOURS": "24 hrs",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "Please call 311 for maintenance requests",
    "LATITUDE": 49.2803243,
    "LONGITUDE": -123.118054,
    "MAINTAINER": "City"
  },
  {
    "PRIMARYIND": 102,
    "PLACE": "Hastings at Carral - Pigeon Park",
    "ADDRESS": "",
    "TYPE": "Automated Public Toilet",
    "PHYSICAL_LOCATION": "NW corner of intersection",
    "SUMMER_HOURS": "24 hrs",
    "WINTER_HOURS": "24 hrs",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "Please call 311 for maintenance requests",
    "LATITUDE": 49.2816384,
    "LONGITUDE": -123.104602,
    "MAINTAINER": "City"
  },
  {
    "PRIMARYIND": 103,
    "PLACE": "Robson at Granville",
    "ADDRESS": "",
    "TYPE": "Automated Public Toilet",
    "PHYSICAL_LOCATION": "NW corner of intersection",
    "SUMMER_HOURS": "24 hrs",
    "WINTER_HOURS": "24 hrs",
    "WHEELCHAIR_ACCESS": "Accessible",
    "NOTE": "Please call 311 for maintenance requests",
    "LATITUDE": 49.2816325,
    "LONGITUDE": -123.120082,
    "MAINTAINER": "City"
  },
  {
    "PRIMARYIND": 104,
    "PLACE": "Bute at Davie",
    "ADDRESS": "",
    "TYPE": "Automated Public Toilet",
    "PHYSICAL_LOCATION": "NE corner of intersection",
    "SUMMER_HOURS": "24 hrs",
    "WINTER_HOURS": "24 hrs",
    "WHEELCHAIR_ACCESS": "None",
    "NOTE": "Please call 311 for maintenance requests",
    "LATITUDE": 49.2818541,
    "LONGITUDE": -123.133141,
    "MAINTAINER": "City"
  },
  {
    "PRIMARYIND": 105,
    "PLACE": "Nelson Park",
    "ADDRESS": "",
    "TYPE": "Automated Public Toilet",
    "PHYSICAL_LOCATION": "West side of park",
    "SUMMER_HOURS": "24 hrs",
    "WINTER_HOURS": "24 hrs",
    "WHEELCHAIR_ACCESS": "Accessible",
    "NOTE": "Please call 311 for maintenance requests",
    "LATITUDE": 49.283378,
    "LONGITUDE": -123.130677,
    "MAINTAINER": "City"
  }]
}];
